### ISSUE TITLE
Bug: Detecta links erroneos al encontrar enlaces tipo mail_to:info@correo.com.

### ISSUE THREAD

**Issue by Myky8** [westial/grepspider#1]
Bug: Detecta links erroneos al encontrar enlaces tipo mail_to:info@correo.com.

Al lanzar una búsqueda en un dominio si encuentra un enlace tipo mail_to aparece links tipo:
- https://www.online.com/terms-and-conditions/amp/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com/info@online.com

**Comment by westial** [comment]
Resuelta en la 0.2.1.
